# Исключения

---

```python
a = [1, 2, 3]

try:
	print(a[3])
except:
	print("Some error occurred")
finally:
	a.clear()
```
[Встроенные классы исключений](https://docs.python.org/3/library/exceptions.html)

---

```python
d = { "pi": 3.14, "chibi": False }

try:
	print(d["cat"])
except KeyError:
	print("Invalid key")
except Exception:
	print("Error occurred")
```

---

```python
def dangerous_func():
	raise NotImplementedError()

try:
	dangerous_func()
except Exception:
	print("Error occurred")
except NotImplementedError:
	print("Function is not implemented")
```
